[build]
functions = "functions"
command = "npm run build"

[functions]
node_bundler = "esbuild"

[context.production]
environment = { NODE_VERSION = "14" }  # Specify the desired Node.js version
[context.deploy-preview]
environment = { NODE_VERSION = "14" }  # Specify the desired Node.js version
